### ISSUE TITLE
QwiqWit: user not being added to room

### ISSUE THREAD

**Issue by tannerkrewson** [tannerkrewson/rocketcrab#36]
@TypesInCode 

![Screenshot 2020-09-10 215525](https://user-images.githubusercontent.com/8444595/92849188-a1a59b00-f3b0-11ea-80d3-a5e30a407797.png)

Two different incognito browsers. If i try to enter a name on the left browser, it asks for a game code

**Comment by tannerkrewson** [comment]
Let me know if you can reproduce or would like any more info. Happy to help, and thanks for looking into this! 😄

**Comment by TypesInCode** [comment]
Looks like the QwiqWit cookie is considered 3rd party in the iframe and is being blocked when in incognito:
https://angel.co/today/stories/chrome-83-arrives-with-redesigned-security-settings-third-party-cookies-blocked-in-incognito-21796

This seems to be by design behavior for Chrome.  It does work out of incognito if you use two different browsers.

**Comment by tannerkrewson** [comment]
oh crap; you're right! i knew that 🤦 just tested and it works great.  thanks! ⭐⭐⭐⭐⭐
